app.name={{buildMeta:appName}}
app.version={{buildMeta:appVersion}}
app.user={{buildMeta:buildUser}}
app.releasedAt={{buildMeta:types.releasedAt}}
git.commit={{buildMeta:gitMeta.commitHash}}
docs.example=\{{buildMeta:appName}}
