package dev.gradienttim.buildmeta

import org.gradle.testkit.runner.BuildResult
import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.io.path.createTempDirectory
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class BuildMetaPluginTest {
    private val projectDir: File = createTempDirectory("buildmeta").toFile()

    private val generatedDir: File
        get() = projectDir.resolve("build/generated/buildmeta/java")

    @AfterTest
    fun cleanup() {
        projectDir.deleteRecursively()
    }

    private fun project(buildMeta: String, extra: String = "") {
        projectDir.resolve("settings.gradle.kts").writeText("rootProject.name = \"test\"")
        projectDir.resolve("build.gradle.kts").writeText(
            """
            plugins {
                java
                id("dev.gradienttim.buildmeta")
            }

            $extra

            buildMeta {
                fallbackPackageName = "com.test"
                $buildMeta
            }
            """.trimIndent(),
        )
    }

    private fun runner(vararg arguments: String): GradleRunner =
        GradleRunner.create()
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withArguments(*arguments, "--configuration-cache", "--stacktrace")

    private fun build(vararg arguments: String): BuildResult = runner(*arguments).build()

    private fun fail(vararg arguments: String): BuildResult = runner(*arguments).buildAndFail()

    @Test
    fun `generates java sources and skips empty buildmetas`() {
        project(
            """
            main {
                field("appName", "App \"1\"")
                field("answer", 42)
                field("appVersion", "1.0") {
                    namingStrategy = dev.gradienttim.buildmeta.meta.FieldMeta.NamingStrategy.SCREAMING_SNAKE_CASE
                }
            }
            register("empty") { }
            """,
        )

        build("compileJava")

        val source = generatedDir.resolve("main/com/test/BuildMeta.java").readText()
        assertContains(source, "// Generated by BuildMeta")
        assertContains(source, "public static final String appName = \"App \\\"1\\\"\";")
        assertContains(source, "public static final int answer = 42;")
        assertContains(source, "public static final String APP_VERSION = \"1.0\";")
        assertFalse(generatedDir.resolve("empty").walk().any { it.isFile })
    }

    @Test
    fun `reads task output providers at execution time`() {
        project(
            """
            main {
                field("value", writer.flatMap { it.output }.map { it.asFile.readText() })
            }
            """,
            """
            abstract class Writer : DefaultTask() {
                @get:Input abstract val text: Property<String>
                @get:OutputFile abstract val output: RegularFileProperty

                @TaskAction
                fun write() = output.get().asFile.writeText(text.get())
            }

            val writer = tasks.register<Writer>("writer") {
                text = providers.gradleProperty("text")
                output = layout.buildDirectory.file("value.txt")
            }
            """,
        )

        build("generateBuildMeta", "-Ptext=first")
        val second = build("generateBuildMeta", "-Ptext=second")

        assertContains(second.output, "Configuration cache entry reused")
        assertContains(generatedDir.resolve("main/com/test/BuildMeta.java").readText(), "value = \"second\";")
    }

    @Test
    fun `reports all problems at once`() {
        project(
            """
            indent = 0
            main {
                field("missing", { null })
                field("unsupported", StringBuilder("x"))
            }
            register("bad") {
                fileName = "not valid"
                packageName = "a..b"
                field("value", 1)
            }
            """,
        )

        val output = fail("resolveBuildMeta").output

        assertContains(output, "Found 5 BuildMeta problem(s)")
        assertContains(output, "indent must be a positive integer")
        assertContains(output, "field 'missing' resolved to null")
        assertContains(output, "field 'unsupported' resolved to an unsupported type")
        assertContains(output, "file name 'not valid' is not a valid identifier")
        assertContains(output, "Package name 'a..b' contains an invalid segment")
    }

    @Test
    fun `rejects invalid buildmeta names`() {
        project("register(\"my meta\") { }")

        assertContains(fail("help").output, "BuildMeta name 'my meta' is not a valid identifier")
    }

    @Test
    fun `replaces placeholders in resources`() {
        project(
            """
            main { field("appName", "App") }
            register("git") { fileName = "Git"; field("hash", "abc") }
            """,
        )
        projectDir.resolve("src/main/resources").apply { mkdirs() }.apply {
            resolve("app.properties").writeText(
                "name={{buildMeta:appName}}\nhash={{buildMeta:git.hash}}\nliteral=\\{{buildMeta:appName}}\n",
            )
            resolve("logo.png").writeText("{{buildMeta:appName}}")
        }

        build("processResources")

        val resources = projectDir.resolve("build/resources/main")
        assertEquals(
            "name=App\nhash=abc\nliteral={{buildMeta:appName}}\n",
            resources.resolve("app.properties").readText(),
        )
        assertTrue(resources.resolve("logo.png").readText().contains("{{buildMeta:appName}}"))
    }
}
